server:
  port: 9092
spring:
  application:
    name: service-hi
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka/
  instance:
    ip-address: 192.168.22.5
    hostname: ${eureka.instance.ip-address}
    health-check-url: ${eureka.instance.hostname}/actuator/health
    instance-id: ${eureka.instance.ip-address}:${server.port}-${spring.application.name}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5